src/main/scala/com/gu/invoicing/refund/Impl.scala, src/main/scala/com/gu/invoicing/refund/Model.scala, src/test/scala/com/gu/invoicing/refund/RoundSuite.scala
Address https://github.com/guardian/invoicing-api/pull/1#discussion_r417154561
Handle at deserialisation level by converting `Double` to `BigDecimal` before any calculations take place:
```
implicit val bigDecimalRW: ReadWriter[BigDecimal] = 
readwriter[Double].bimap[BigDecimal](_.toDouble, double => BigDecimal(double.toString))
```
=> Calculate money with BigDecimal

build.sbt, cfn.yaml, src/main/scala/com/gu/invoicing/invoice/Cli.scala, src/main/scala/com/gu/invoicing/invoice/Impl.scala, src/main/scala/com/gu/invoicing/invoice/Lambda.scala, src/main/scala/com/gu/invoicing/invoice/Log.scala, src/main/scala/com/gu/invoicing/invoice/Model.scala, src/main/scala/com/gu/invoicing/invoice/Program.scala, src/main/scala/com/gu/invoicing/invoice/README.md
https://trello.com/c/ggqXe1rg/1492-goal-expose-invoices-for-the-billing-tab
Return 
```
{
"invoices": [
{
"invoiceId": "1234567899qwertyuio",
"subscriptionName": "A-S0000000",
"date": "2020-08-05",
"pdfPath": "invoices/afileId",
"price": 813.48,
"paymentMethod": "BankTransfer",
"last4": "9911"
}
]
}
```
when server-side of manage-frontend requests `GET /invoices`, which will be rendered as something like
- The field `"pdfPath":  "invoices/afileId"` corresponds to `fileId` of Zuora [GET_InvoiceFiles](https://www.zuora.com/developer/api-reference/#operation/GET_InvoiceFiles) which will be used to download the PDF invoice file (implemented in separate PR). 
- MMA will need to send an x-identity-id + API key + [AWS signature](https://github.com/guardian/manage-frontend/pull/465).
- Main …
=> GET /invoices/{accountId}

build.sbt, cfn.yaml, src/main/scala/com/gu/invoicing/invoice/Model.scala, src/main/scala/com/gu/invoicing/pdf/Cli.scala, src/main/scala/com/gu/invoicing/pdf/Impl.scala, src/main/scala/com/gu/invoicing/pdf/Lambda.scala, src/main/scala/com/gu/invoicing/pdf/Log.scala, src/main/scala/com/gu/invoicing/pdf/Model.scala, src/main/scala/com/gu/invoicing/pdf/Program.scala, src/main/scala/com/gu/invoicing/pdf/README.md
* https://trello.com/c/ggqXe1rg/1492-goal-expose-invoices-for-the-billing-tab
* Related PR: https://github.com/guardian/invoicing-api/pull/7
* If signed in user clicks on invoice PDF link in manage-frontend, then invoicing-api responds with `application/pdf`
* Main business logic is in `Program.scala`
* Note this also changes `GET /invoices` response to `"pdfPath": "anInvoiceId"`  instead of `"pdfPath": "aFileId"`
See `com.gu.invoicing/pdf/README.md`
- Besides required secrets, invoicing-api will perform validation against that the requested invoice belongs to the requesting identity, by independently retrieving `identityId` from `invoiceId` and checking against `x-identity-id` header added by server-side of manage-frontend.
- Alarm on any error
=> GET /invoices/{invoiceId} PDF

src/main/scala/com/gu/invoicing/invoice/Impl.scala, src/main/scala/com/gu/invoicing/invoice/Model.scala, src/main/scala/com/gu/invoicing/invoice/Program.scala
```
* ... handle the rare edge case of user being invoiced for
* multiple subscriptions in a single invoice. Such invoices have a single price,
* however MMA design displays invoices grouped by product. This happens in the following cases:
*   - customer has been through a conversation with a CSR on the phone who would have explained that there would be a product transition in their next bill; or
*   - it's a result of some kind of manual account for a special reason (e.g. GW agent)
*
```
Response contains `hasMultipleSubs` flag
```
{
"invoiceId": "123456789",
"subscriptionName": "A-S00000003",
"date": "2020-06-04",
"pdfPath": "invoices/123456789",
"price": 59.49,
"paymentMethod": "PayPal",
"hasMultipleSubs": true
},
{
"invoiceId": "123456789",
"subscriptionName": "A-S00000002",
"date": …
```
=> Support invoices with multiple subscriptions

src/main/scala/com/gu/invoicing/common/ZuoraAuth.scala
List invoices endpoint is hit frequently which seems to keep lambda container and JVM warm long enough to be re-used for the next invocation. It seem to keep it warm long enough for the Zuora access token to expire after one hour. Because previously access token was `val` it would not get a new one. 
List invoices is hit so frequently because even if user does not have paid product, manage-frontend makes the request (which then returns empty list). Ideally manage-frontend would not make this call unnecessarily.
```
export AWS_DEFAULT_REGION=eu-west-1 && awslogs get --profile membership /aws/lambda/invoicing-api-invoices-PROD --watch
```
=> Refresh Zuora access token periodically

src/main/scala/com/gu/invoicing/common/Retry.scala, src/main/scala/com/gu/invoicing/common/ZuoraAuth.scala
* Related https://github.com/guardian/invoicing-api/pull/16
* Handle temporary outages by not updating token cache. Token expires after one hour but we refresh every 5 minutes so reusing previous one should be ok.
Because of outages such as https://trust.zuora.com/incidents/76mw16rl3qrk
=> Retry Zuora authentication

src/main/scala/com/gu/invoicing/common/Retry.scala, src/main/scala/com/gu/invoicing/common/ZuoraAuth.scala, src/main/scala/com/gu/invoicing/invoice/Program.scala, src/main/scala/com/gu/invoicing/pdf/Program.scala
Zuora requests are regularly failing. 
1. `deployAwsLambda DEV`
2. `GET {{invoicingApiUrl}}/invoices` with fresh janus credentials and correct identityId
Less alarms.
Retrying GET is safe.
=> Retry all GET requests

.gitignore, project/build.properties, project/plugins.sbt
- Updates to sbt 1.4.0 which provides thin client
- Adds bloop plugin for even greater speedup in compilation
* `sbt --client`
* `bloop compile root`
Faster build responses.
No major risk.
=> Update to sbt 1.4.0

build.sbt, cfn.yaml, riff-raff.yaml, src/main/scala/com/gu/invoicing/nextinvoicedate/Cli.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/Impl.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/Lambda.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/Model.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/Program.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/README.md, src/test/scala/com/gu/invoicing/nextinvoicedate/NextInvoiceDateSuite.scala
https://trello.com/c/i0a10FyJ/1542-replace-billing-date-calculation-in-support-service-lambdas-with-calls-to-billing-preview-endpoint
Provides the ability to predict the next invoice date even if bill run has not happened, that is when `chargedThroughDate` is null, by utilising `/operations/billing-preview` Zuora API.
```
GET /next-invoice-date/A-S00000000 HTTP/1.1
Host: https://{apiGatewayId}.execute-api.{region}.amazonaws.com/{stage}
Content-Type: application/json
x-api-key: ***********
```
responds with
```
{
"nextInvoiceDate": "2020-10-27"
}
```
* Follow the instructions in the readme, or simply hit the above endpoint with Postman.
Hopefully removal of custom (and buggy) implementation of preview functionality from support-service-lambdas credit processor.
There is a bit of …
=> GET /next-invoice-date/{subscriptionName}

src/main/scala/com/gu/invoicing/common/Http.scala, src/main/scala/com/gu/invoicing/invoice/Impl.scala, src/main/scala/com/gu/invoicing/nextinvoicedate/Impl.scala, src/main/scala/com/gu/invoicing/pdf/Impl.scala, src/main/scala/com/gu/invoicing/refund/Impl.scala
Increases limits in attempt to address frequent Zuora socket timeouts.
HTTP client with longer timeouts has already been tested on refund endpoint, this PR simply uses it throughout all the endpoints. 
Less alarms due to socket timeout.
No risk.
=> Increase HTTP client timeouts

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Model.scala, src/main/scala/com/gu/invoicing/preview/Program.scala, src/test/scala/com/gu/invoicing/preview/PricePerPublicationSuite.scala
* Unfortunately billing-preview does [not](https://www.zuora.com/developer/api-reference/#operation/POST_BillingPreview) calculate tax
> This field returns 0 becasue the BillingPreview operation does not calculate taxes for charges in the subscription.
* Zuora support provided [no solution ](https://support.zuora.com/hc/en-us/requests/281646).
* As a workaround we obtain `chargeAmount` inclusive of tax via `RatePlanCharge`.
Issue can be replicate for, say, Guardian Weekly billed to Quebec, Canada . For example, price of single 6-for-6 Publication would be calculated as 0.87 CAD instead of 1 CAD.
Satisfy test in prod currently running as part of https://github.com/guardian/support-service-lambdas/pull/751
No major risk.
=> Workaround billing-preview not calculating tax

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Program.scala
`originalChargeId` returned from `subscriptions/A-S00000000` turns out to be mutable so it is not a reliable way of joining past invoice items with `RatePlanCharge`s. Turns out `taxAmount` is correctly populated for past `InvoiceItem`s so we simply use that to determine the tax. The way we determine tax for future `InvoiceItem`s remains unchanged from https://github.com/guardian/invoicing-api/pull/25 workaround.
Currently I am depending on [`testInProdPreviewPublications`](https://github.com/guardian/support-service-lambdas/pull/751) to obtain failing Subscriptions. However I am not quite sure what causes `originalChargeId` to change...
No risk until switchover.
=> Separate tax calculation for past and future InvoiceItems

Dockerfile, build.sbt
TeamCity can build correct linux native-image as `sbt-native-image` executes within linux container. However when building on MacOS then `sbt-native-image` will build executable native to MacOS which will not work in Amazon Linux lambda. This PR provides a docker image which can be used to build linux invoice-api native lambdas on any platform. 
1. Get fresh janus credentials
1. Install docker
1. Give docker more memory (I have gave it 6.25)
1. execute `deployAwsLambda` which will build the native image and upload lambdas
Corresponding manual steps would be
1. `docker build -t invoicing-api .` (only necessary first time and if there are any changes to `Dockerfile`)
1.  `docker run -it -v "$(pwd -P)":/invoicing-api invoicing-api bash` 
1. `sbt packageNativeAwsImage`
1. …
=> Build native linux image from any platform via Docker

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Program.scala
* We should select the InvoiceItem if either its `serviceStartDate` or `serviceEndDate` falls within the input range (provided from query parameters).
* Secondary bug fix: remove duplicated tax calculation
Tested via CLI against subscriptions flagged by  [`testInProdPreviewPublications`](https://trello.com/c/o6Q3AQd3/1760-monitor-test-in-production-tip-for-new-billing-preview-functionality)
Less discrepancies in `testInProdPreviewPublications`
No risk.
=> Fix checking if InvoiceItem falls within relevant range

src/main/scala/com/gu/invoicing/preview/Cli.scala, src/main/scala/com/gu/invoicing/preview/Impl.scala
* Exclude past invoice items with serviceEndDate before requested start date of range 
* Exclude past invoice items with serviceStartDate after requested end date of range
=> Fix filtering of past invoice items

src/main/scala/com/gu/invoicing/preview/Impl.scala
* Previously it would fail if currently active InvoiceItem was the last InvoiceItem in the range, because in this case `_.serviceStartDate.isAfter(today)` would be false
* This PR changes determination of nextInvoiceDate by first identifying precisely the current active InvoiceItem and taking the day after `serviceEndDate`.
=> Find nextInvoiceDate using currently active InvoiceItem

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Program.scala
getFutureInvoiceItems would previously return invoice items of all subscriptions (even if account has multiple different subscriptions) but we need to narrow it down to a particular subscription requested by the user.
=> Invoice items should not include multiple subscriptions

src/main/scala/com/gu/invoicing/preview/Impl.scala
* https://github.com/guardian/zuora-6for6-modifier
* During Christmas holidays some subscribers may miss one issue but we have to honour 6 issues for 6 weeks so billing period might be extended from 6 weeks to 7 weeks. Without accounting for this 7 weeks billing period, subscribers might be credited 0.86 instead of 1.
`testInProdPreviewPublications` identified a problematic subscriptions which was then tested locally via CLI.scala.
=> 6 for 6 is sometimes 7 weeks due to extension during Christmas holidays

src/main/scala/com/gu/invoicing/preview/Impl.scala
* Negative invoices can be created, for example, when holiday spans multiple billing periods corresponding to multiple invoices, but all the credits are applied to a single invoice, which might cause too much credit to be applied to a single invoice. For example, sum of positive invoice items might be 5, but the sum of negative invoice items might be -10, in which case total invoice amount will be -5. Such an invoice is still a valid invoice which contains relevant dates for calculation of individual publications so should not be excluded.
* Related info regarding negative invoices
*   https://github.com/guardian/zuora-creditor
*   `ALARM: zuora-creditor PROD: number of Invoices credited > 0`
=> Do not exclude negative invoices

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Program.scala
billing-preview call is not performant when target date is far in the future. It can take more than 30 seconds so the holiday-stop-api times out
```
testInProdPreviewPublications failed A00000000?startDate=2021-03-08&endDate=2021-03-08 because invoicing-api error: ZuoraApiFailure({"message": "Endpoint request timed out"})
```
It might be sufficient to simply use the user provided end date of the range now.
`testInProdPreviewPublications`
=> Try sooner targetDate because billing-preview cant take >30 seconds

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Model.scala
[GET_TransactionInvoice](https://www.zuora.com/developer/api-reference/#operation/GET_TransactionInvoice) used to fetch past InvoiceItems returns paginated results when there are too many records
```
pageSize   integer <= 40
Default: 20
Number of rows returned per page.
```
Tested on subscriptions flagged by `testInProdPreviewPublications`
=> Handle pagination of past InvoiceItems

src/main/scala/com/gu/invoicing/preview/Impl.scala, src/main/scala/com/gu/invoicing/preview/Model.scala, src/main/scala/com/gu/invoicing/preview/Program.scala
There are are some (low frequency) cases where account associated with subscription (`accountId`) is different from account associated with invoices (`invoiceOwnerAccountId`), so fetching InvoiceItems from account that does not own the invoices would return empty list.
Most of these are not auto-renewing so credit request should be [blocked](https://github.com/guardian/support-service-lambdas/blob/5b53dc194f1c950a8d5864e8c977f939415a9ed7/handlers/holiday-stop-processor/src/test/scala/com/gu/holidaystopprocessor/HolidayStopProcessTest.scala#L131) at the point of creation anyways.
Relevant subs could be identifies like so
```
SELECT * 
FROM clean.zuora_subscription
WHERE account_id <> invoice_owner_id
AND status = 'Active'
AND auto_renew = true
```
In majority of cases `accountId = …
=> Account that owns invoices might differ from account that owns the subscription

src/main/scala/com/gu/invoicing/preview/Impl.scala
Just a safety net in case incorrect `nextInvoiceDate` is calculated.
=> NextInvoiceDate should not be before today

.gitignore, .scalafmt.conf, build.sbt, cfn.yaml, riff-raff.yaml, src/main/scala/bootstrap.scala, src/main/scala/com/gu/invoicing/refundErroneousPayment/Impl.scala, src/main/scala/com/gu/invoicing/refundErroneousPayment/Lambda.scala, src/main/scala/com/gu/invoicing/refundErroneousPayment/Model.scala, src/main/scala/com/gu/invoicing/refundErroneousPayment/Program.scala, src/main/scala/com/gu/invoicing/refundErroneousPayment/README.md
This adds a refunding endpoint specifically for cases where a payment was collected inadvertently and now needs to be refunded and the account balance corrected to avoid future collection attempts.
Tested in UAT.
=> Add endpoint to refund erroneous payments

src/main/scala/com/gu/invoicing/refundErroneousPayment/Lambda.scala
Function has multiple arguments so needed a bit of a fix-up to compile.
=> Fix function call

src/main/scala/com/gu/invoicing/common/ZuoraAuth.scala, src/main/scala/com/gu/invoicing/pdf/Cli.scala, src/main/scala/com/gu/invoicing/pdf/Impl.scala, src/main/scala/com/gu/invoicing/pdf/Model.scala, src/main/scala/com/gu/invoicing/pdf/Program.scala
Changes to instruct Zuora to regenerate the invoice PDF if it has been using the wrong template ID in the past.
This action is too impractical to backfill eagerly as it would require updating ~54K accounts and ~226K invoices, and the regeneration of the PDF takes about 5 seconds. Only about 1000 customers out of that 55,000 will ever download an invoice, so I've decided it's best to do the regeneration on-demand rather than backfilling. I believe this API services Salesforce as well as Manage My Account.
1. Have an AUD subscription with an invoice generated via the UK company Invoice Template.
2. Log in to the account for that subscription and visit the [invoice download page](url) within Manage My Account
3. Click to download the invoice - it should take a long time ~ 20 seconds to …
=> Changes to instruct Zuora to regenerate the invoice PDF if necessary for Australian users

cfn.yaml
We were having trouble with Auth not working for these lambdas to zuora, even after updating in SSM.
Having looked into it, the version of the parameter in SSM was hard coded in the CFN as `1`, meaning the updated one was not used.
https://eu-west-1.console.aws.amazon.com/systems-manager/parameters/invoicing-api/CODE/config/description?region=eu-west-1&tab=Table
This PR updates the CFN to use the version specified.
I know it has been a trend in the past, but overall it seems like a faff to use CFN dynamic references for config, rather than just pulling it directly from the service in the code.  If it it pulled in startup, it might be slightly slower, but it means it's easier to run it locally, and everything is always up to date.  I'd be interested to know if there are strong arguments in …
=> use updated sandbox zuora config for CODE

src/main/scala/com/gu/invoicing/refund/Impl.scala, src/test/scala/com/gu/invoicing/refund/SpreadRefundAcrossItemsSpec.scala
In #184 the `AdjustmentDate` of an Invoice Item Adjustment was made to align with the date of the original invoice.
This introduces a bug where if a refund is attempted against a payment made in the previous month, the refund succeeds but the subsequent adjustment fails due to a `ACCOUNTING_PERIOD_CLOSED` error. This is because the AdjustmentDate, set to the original charge date, is in the previous accounting period which closes at month end. 
The AdjustmentDate should ALWAYS be set to the current date to avoid this.
This error crops up fairly often in the first half of each month, with 66 in the past 6 months at time of writing:
The `AdjustmentDate` for the separate tax adjustment is still set correctly to be the current date, so often this will fail partially:
The impact on the customer …
=> Set Adjustment Date to current date, not date of original charge

cfn.yaml, src/main/scala/com/gu/invoicing/refund/README.md
1. migrates alarms to use the new SNS topic. This means the alarms will go to the growth team's google chat channel
2. removes the refund lambda alarm. This lambda fails frequently because subscriptions are not in the correct state for refunding, e.g. pending direct debit payment. It's up to the calling lambda (in product-move-api) to retry these and handle errors.
Note - we believe the refund lambda logic could be moved into the relevant product-move-api lambda, as this is the only service that uses it. There may be other lambdas in this project that could also be moved.
=> Migrate alarms

cfn.yaml
Adjusts the thresholds for the alarms related to invoices. They were alarming for each error in a 5 minute period, but this changes to alarm only when there are at least 5 errors in a 15 minute period.
Zuora is occassionally slow to respond, and it is not unusual for it to have a complete hiccup for a few seconds, but generally it recovers fairly quickly. We are only really interested if these endpoints are consistently failing for a large number of requests and/or for a long period of time.
Example recent errors from the [pdf](https://github.com/guardian/invoicing-api/blob/main/src/main/scala/com/gu/invoicing/pdf) endpoint:
Our alarms should be less noisy.
=> Increase alarm thresholds for invoice endpoints

.gitignore, src/main/scala/com/gu/invoicing/common/ZuoraAuth.scala, src/main/scala/com/gu/invoicing/pdf/Impl.scala, src/main/scala/com/gu/invoicing/pdf/Model.scala, src/main/scala/com/gu/invoicing/pdf/Program.scala
[Trello](https://trello.com/c/h7MX4D5w/260-remove-all-references-to-hard-coded-invoice-template-ids-and-move-all-customers-to-new-invoice-template)
This removes all references to hard-coded invoice template IDs.
We have recently created a [generic HTML template](https://github.com/guardian/zuora-config/blob/main/finance/invoice-templates/system-default.html) that will be used by default for all products / accounts.
=> feat: remove hard-coded invoice template IDs
